export const designTokens = {
  color: {
    background: 'var(--color-background)',
    primary: 'var(--color-primary)',
    medicalCyan: 'var(--color-medical-cyan)',
    medicalTeal: 'var(--color-medical-teal)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    danger: 'var(--color-danger)',
    glass: 'var(--color-glass)',
    glassBorder: 'var(--color-glass-border)',
  },
  app: {
    canvas: 'var(--clinora-bg-canvas)',
    chrome: 'var(--clinora-bg-chrome)',
    surface1: 'var(--clinora-surface-1)',
    surface2: 'var(--clinora-surface-2)',
    heroSurface: 'var(--clinora-surface-hero)',
    nestedSurface: 'var(--clinora-surface-nested)',
    hoverSurface: 'var(--clinora-surface-hover)',
    subtleBorder: 'var(--clinora-border-subtle)',
    interactiveBorder: 'var(--clinora-border-interactive)',
    primaryText: 'var(--clinora-text-primary)',
    mutedText: 'var(--clinora-text-muted)',
    faintText: 'var(--clinora-text-faint)',
    cyan: 'var(--clinora-accent-cyan)',
    teal: 'var(--clinora-accent-teal)',
    primaryGradient: 'var(--clinora-primary-gradient)',
    success: 'var(--clinora-success)',
    warning: 'var(--clinora-warning)',
    danger: 'var(--clinora-danger)',
  },
  layout: {
    maxWidth: 'var(--container-max)',
    containerPadding: 'var(--container-padding)',
    columns: 12,
  },
  radius: {
    component: 'var(--radius-component)',
    largeCard: 'var(--radius-card-large)',
    small: 'var(--clinora-radius-sm)',
    medium: 'var(--clinora-radius-md)',
    large: 'var(--clinora-radius-lg)',
    pill: 'var(--clinora-radius-pill)',
  },
  spacing: {
    section: 'var(--clinora-space-section)',
    group: 'var(--clinora-space-group)',
    card: 'var(--clinora-space-card)',
  },
  glass: {
    blur: 'var(--blur-glass)',
    shadow: 'var(--shadow-glass)',
  },
  motion: {
    fast: 'var(--clinora-motion-hover)',
    hover: 'var(--clinora-motion-hover)',
    panel: 'var(--clinora-motion-panel)',
    page: 'var(--clinora-motion-page)',
    slow: 'var(--clinora-motion-slow)',
  },
  motif: {
    ambient: {
      primary: 'var(--clinora-motif-primary-ambient)',
      secondary: 'var(--clinora-motif-secondary-ambient)',
      marks: 'var(--clinora-motif-marks-ambient)',
    },
    supporting: {
      primary: 'var(--clinora-motif-primary-supporting)',
      secondary: 'var(--clinora-motif-secondary-supporting)',
      marks: 'var(--clinora-motif-marks-supporting)',
    },
    focused: {
      primary: 'var(--clinora-motif-primary-focused)',
      secondary: 'var(--clinora-motif-secondary-focused)',
      marks: 'var(--clinora-motif-marks-focused)',
    },
    schematic: 'var(--clinora-schematic-opacity)',
  },
  breakpoint: {
    mobile: '390px',
    tablet: '768px',
    laptop: '1024px',
    desktop: '1440px',
  },
} as const;
