package com.clinora.audit;

public enum AuthAuditAction {
    PATIENT_REGISTERED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    TOKEN_REFRESHED,
    LOGOUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    SESSION_REVOKED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,
    ACCESS_APPLICATION_CREATED,
    ACCESS_APPLICATION_VERIFICATION_SENT,
    ACCESS_APPLICATION_EMAIL_VERIFIED,
    ACCESS_APPLICATION_ACCESS_LINK_REQUESTED,
    ACCESS_APPLICATION_SESSION_ESTABLISHED,
    ACCESS_APPLICATION_DOCUMENT_UPLOADED,
    ACCESS_APPLICATION_DOCUMENT_DELETED,
    ACCESS_APPLICATION_SUBMITTED,
    ACCESS_APPLICATION_WITHDRAWN,
    SYSTEM_ADMIN_BOOTSTRAPPED
}
