package com.clinora.audit;

public enum AuthAuditAction {
    PATIENT_REGISTERED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    TOKEN_REFRESHED,
    LOGOUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    SESSION_REVOKED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED
}
