package com.clinora.access.domain;

public enum ApplicationEventType {
    APPLICATION_CREATED, EMAIL_VERIFICATION_SENT, EMAIL_VERIFIED, ACCESS_LINK_REQUESTED, SESSION_ESTABLISHED,
    PROFILE_UPDATED, DOCUMENT_UPLOADED, DOCUMENT_DELETED, SUBMITTED, WITHDRAWN,
    REVIEW_STARTED, MORE_INFO_REQUESTED
}
