package com.clinora.access.domain;

public enum ApplicationEventType {
    APPLICATION_CREATED, EMAIL_VERIFICATION_SENT, EMAIL_VERIFIED, ACCESS_LINK_REQUESTED, SESSION_ESTABLISHED,
    PROFILE_UPDATED, DOCUMENT_UPLOADED, DOCUMENT_DELETED, SUBMITTED, WITHDRAWN,
    REVIEW_STARTED, MORE_INFO_REQUESTED,
    DOCTOR_INTERVIEW_REQUIRED, DOCTOR_INTERVIEW_SCHEDULED, DOCTOR_INTERVIEW_RESCHEDULE_REQUESTED,
    DOCTOR_INTERVIEW_RESCHEDULED, DOCTOR_INTERVIEW_CANCELLED, DOCTOR_INTERVIEW_COMPLETED,
    DOCTOR_INTERVIEW_NO_SHOW, DOCTOR_INTERVIEW_REMINDER_SENT
}
